title: Your awesome title
author: Abdul-Hadi Siddiqui
email: asidd14@ocdsb.com
description: > # this means to ignore newlines until "baseurl:"
  Hockey, Soccer, Basket-ball, and more. You name it, you will find 
  headlines regarding thsese aports on our website.

# social links
github_username:  ULT01

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
